version: '3.3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4
    volumes:
#      - path to your wp project
    ports:
      - "80:80"
      - "9000:9000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: DB_NAME
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 12345678
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - 8081:80
    environment:
      UPLOAD_LIMIT: 1024M
      MYSQL_ROOT_PASSWORD:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user